import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import {
  Box,
  Button,
  Drawer,
  IconButton,
  Stack,
  Typography,
  useTheme,
} from "@mui/material";
import React, { useState } from "react";
import Licencia from "../componentes/Licencia";
import BotonLicencia from "../componentes/BotonLicencia";
import Link from "next/link";
import useMediaQuery from "@mui/material/useMediaQuery";

const inter = Inter({ subsets: ["latin"] });

export const licencias = [
  {
    nombre: "Licencia de 1 mes",
    duracion: "1 mes",
    poder: "70%",
    tiempoEstimado: "6hs",
    link: "mes",
    precio: "$25",
  },
  {
    nombre: "Licencia de 3 meses",
    duracion: "3 meses",
    poder: "80%",
    tiempoEstimado: "4hs",
    link: "3-meses",
    precio: "$45",
  },
  {
    nombre: "Licencia de 1 año",
    duracion: "1 año",
    poder: "90%",
    tiempoEstimado: "3hs",
    link: "anual",
    precio: "$100",
  },
  {
    nombre: "Licencia de por vida (socio)",
    duracion: "De por vida",
    poder: "99%",
    tiempoEstimado: "1hs",
    link: "socio",
    precio: "$200",
  },
];

export default function Home() {
  const [licencia, setLicencia] = useState("Licencia de 1 mes");
  const [drawerOpen, setDrawerOpen] = useState(false);

  const theme = useTheme();
  const grande = useMediaQuery(theme.breakpoints.up("md"));
  console.log(grande);
  // https://i.pngimg.me/thumb/f/720/m2i8G6G6b1m2A0G6.jpg
  return (
    <>
      <Head>
        <title>Wallet Hunter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          backgroundColor: "#181a20",
          color: "#e5e7eb",
          paddingLeft: 25,
          paddingRight: 25,
        }}
      >
        <Stack
          py={4}
          direction="row"
          alignItems="center"
          justifyContent="space-between"
        >
          <Typography color="#e5e7eb" fontWeight={600}>
            Wallet Hunter
          </Typography>
          {grande && (
            <Stack display="flex" alignItems="center" gap={2} direction="row">
              <Link
                href="#como-funciona"
                style={{
                  cursor: "pointer",
                  textDecoration: "none",
                  color: "#e5e7eb",
                  fontWeight: 600,
                  userSelect: "none",
                  "&:hover": {
                    textDecoration: "underline",
                  },
                }}
              >
                <Typography color="#e5e7eb" fontWeight={600}>
                  Como funciona
                </Typography>
              </Link>
              <Link
                href="#precios"
                style={{
                  cursor: "pointer",
                  textDecoration: "none",
                  color: "#e5e7eb",
                  fontWeight: 600,
                  userSelect: "none",
                  "&:hover": {
                    textDecoration: "underline",
                  },
                }}
              >
                <Typography fontWeight={600}>Precios</Typography>
              </Link>
              <Link
                href="#preguntas=frecuentes"
                style={{
                  cursor: "pointer",
                  textDecoration: "none",
                  color: "#e5e7eb",
                  fontWeight: 600,
                  userSelect: "none",

                  "&:hover": {
                    textDecoration: "underline",
                  },
                }}
              >
                <Typography fontWeight={600}>Preguntas</Typography>
              </Link>
              <Link
                href="https://t.me/wallethunterr?text=Hola%20estoy%20interesado"
                target="_blank"
                style={{
                  cursor: "pointer",
                  textDecoration: "none",
                  color: "#e5e7eb",
                  fontWeight: 600,
                  userSelect: "none",
                  backgroundColor: "#fcd535",
                  color: "#1e2329",
                  "&:hover": {
                    textDecoration: "underline",
                  },
                }}
              >
                <Typography fontWeight={600} p={1}>
                  Contactarse
                </Typography>
              </Link>
              {/* <Button>Contactarse</Button> */}
            </Stack>
          )}

          {!grande && (
            <Box display={{ base: "block", md: "none" }}>
              <IconButton
                color="inherit"
                aria-label="menu"
                onClick={() => setDrawerOpen(true)}
                sx={{ display: { md: "none" } }}
              >
                <img
                  width="25px"
                  src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Hamburger_icon_white.svg/1024px-Hamburger_icon_white.svg.png"
                />
              </IconButton>
              <Drawer
                anchor="right"
                open={drawerOpen}
                onClose={() => setDrawerOpen(false)}
              >
                <Stack
                  p={2}
                  height="100%"
                  gap={2}
                  sx={{ width: 250, backgroundColor: "#181a20" }}
                  role="presentation"
                  onClick={() => setDrawerOpen(false)}
                  onKeyDown={() => setDrawerOpen(false)}
                >
                  <Typography color="#e5e7eb" fontWeight={600}>
                    Wallet Hunter
                  </Typography>
                  <Link
                    href="#como-funciona"
                    style={{
                      cursor: "pointer",
                      textDecoration: "none",
                      color: "#e5e7eb",
                      fontWeight: 600,
                      userSelect: "none",
                      "&:hover": {
                        textDecoration: "underline",
                      },
                    }}
                  >
                    <Typography color="#e5e7eb" fontWeight={600}>
                      Como funciona
                    </Typography>
                  </Link>
                  <Link
                    href="#precios"
                    style={{
                      cursor: "pointer",
                      textDecoration: "none",
                      color: "#e5e7eb",
                      fontWeight: 600,
                      userSelect: "none",
                      "&:hover": {
                        textDecoration: "underline",
                      },
                    }}
                  >
                    <Typography fontWeight={600}>Precios</Typography>
                  </Link>
                  <Link
                    href="#preguntas=frecuentes"
                    style={{
                      cursor: "pointer",
                      textDecoration: "none",
                      color: "#e5e7eb",
                      fontWeight: 600,
                      userSelect: "none",

                      "&:hover": {
                        textDecoration: "underline",
                      },
                    }}
                  >
                    <Typography fontWeight={600}>Preguntas</Typography>
                  </Link>
                  <Link
                    href="https://t.me/wallethunterr?text=Hola%20estoy%20interesado"
                    target="_blank"
                    style={{
                      cursor: "pointer",
                      textDecoration: "none",
                      color: "#e5e7eb",
                      fontWeight: 600,
                      userSelect: "none",
                      backgroundColor: "#fcd535",
                      color: "#1e2329",
                      "&:hover": {
                        textDecoration: "underline",
                      },
                    }}
                  >
                    <Typography fontWeight={600} p={1}>
                      Contactarse
                    </Typography>
                  </Link>
                </Stack>
              </Drawer>
            </Box>
          )}
        </Stack>

        <Stack
          direction={{ base: "column", md: "row" }}
          alignItems="center"
          gap={2}
          py={5}
          minHeight="80vh"
        >
          <Box width={{ base: "90%", md: "60%" }}>
            <Typography fontSize={36} mb={1} fontWeight={700}>
              Gana criptomonedas de forma automática
            </Typography>
            <Typography mb={2} fontWeight={500}>
              Wallet Hunter es un software de alta calidad y con tecnología
              blockchain que busca billeteras de criptomonedas abandonadas en la
              nube y las mina de forma automatica
            </Typography>
            <Link
              href="#como-funciona"
              style={{
                cursor: "pointer",
                textDecoration: "none",
                color: "#e5e7eb",
                fontWeight: 600,
                userSelect: "none",

                "&:hover": {
                  textDecoration: "underline",
                },
              }}
            >
              <Button
                variant="contained"
                style={{ backgroundColor: "#fcd535", color: "#1e2329" }}
              >
                Más información
              </Button>
            </Link>
          </Box>
          <Box width="40%" display="flex" justifyContent="center">
            <img
              src="https://i.pinimg.com/originals/a0/26/1b/a0261b885cfba5a65c675c33327acf5a.png"
              alt=""
              style={{ width: "280px" }}
            />
          </Box>
        </Stack>
        <Stack id="como-funciona">
          <Typography mb={2} fontWeight={600} fontSize={25}>
            ¿Como funciona?
          </Typography>
          <Stack
            alignItems="center"
            gap={2}
            direction={{ base: "column", md: "row" }}
            mb={10}
          >
            <Box width={{ base: "90%", md: "70%" }} textAlign={"left"}>
              <Typography fontWeight={600} fontSize={20}>
                Wallet Hunter es la solucion para aquellas personas que quieren
                adentrarse en el mundo de las criptomonedas. Disenado con la mas
                avanzada tecnologia blockchain, este software se encarga de
                encontrar y extraer criptomonedas en la nube de forma exitosa y
                depositarlas en tu wallet de BTC, ETC, USDC o BNB.
              </Typography>
            </Box>
            <Box width="30%" display="flex" justifyContent="center">
              <img
                src="https://static.vecteezy.com/system/resources/previews/010/950/246/original/realistic-illustration-of-a-floating-astronaut-illustrated-in-cartoon-style-for-futuristic-and-modern-themes-png.png"
                alt=""
                style={{ width: "280px" }}
              />
            </Box>
          </Stack>
          <Stack
            alignItems="center"
            gap={2}
            direction={{ base: "column-reverse", md: "row" }}
            mb={10}
          >
            <Box width="30%" display="flex" justifyContent="center">
              <img
                src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Cartoon-Astronaut.svg/1697px-Cartoon-Astronaut.svg.png"
                alt=""
                style={{ width: "280px" }}
              />
            </Box>
            <Box width={{ base: "90%", md: "70%" }} textAlign={"left"}>
              <Typography fontWeight={600} fontSize={20}>
                Wallet Hunter funciona por licencias, llaves especiales que
                necesitas para usar el programa. Cada una tiene un poder de
                busqueda y una fecha de vencimiento, cuanto mas grande sea el
                poder de busqueda, mas podras buscar y mas posibilidades tienes
                de ganar dinero. Cada licencia es única y solo se puede usar en
                un dispositivo. Si intentas usar la misma licencia en dos
                computadoras iguales, el sistema bloqueará la licencia.
              </Typography>
            </Box>
          </Stack>
        </Stack>

        {/*  */}
        <Stack py={4} id="precios">
          <Typography fontWeight={600} fontSize={25} mb={1}>
            Precios
          </Typography>
          <Typography fontWeight={600} fontSize={20} mb={5}>
            Selecciona tu licencia
          </Typography>

          <Stack gap={5} direction={{ base: "column", md: "row" }}>
            <Stack
              width={{ base: "100%", md: "50%" }}
              alignItems={"flex-start"}
              gap={2}
              flexGrow={1}
            >
              {licencias.map((x) => (
                <BotonLicencia
                  x={x}
                  setLicencia={setLicencia}
                  licencia={licencia}
                />
              ))}
            </Stack>
            <Box
              width={{ base: "100%", md: "50%" }}
              display="flex"
              justifyContent="center"
            >
              <Licencia nombre={licencia} />
            </Box>
          </Stack>
        </Stack>

        {/*  */}
        <Stack
          style={{ backgroundColor: "#eaecf0" }}
          direction={{ base: "column", md: "row" }}
          alignItems={"center"}
          justifyContent={"space-between"}
          gap={2}
          my={15}
          p={2}
          borderRadius={5}
        >
          <Typography fontWeight={600} fontSize={25} color="black !important">
            Comienza a generar tus ingresos desde tu casa Escribemos ahora mismo
          </Typography>
          <Link
            href="https://t.me/wallethunterr?text=Hola%20estoy%20interesado"
            target="_blank"
            style={{
              cursor: "pointer",
              textDecoration: "none",
              color: "#e5e7eb",
              fontWeight: 600,
              userSelect: "none",
              backgroundColor: "#fcd535",
              color: "#1e2329",
              "&:hover": {
                textDecoration: "underline",
              },
            }}
          >
            <Button
              variant="contained"
              style={{ backgroundColor: "#fcd535", color: "#1e2329" }}
            >
              Contactarse
            </Button>
          </Link>
        </Stack>
        {/*  */}
        <Stack my={4} id="preguntas=frecuentes">
          <Typography fontWeight={600} fontSize={25} mb={5}>
            Preguntas Frecuentes
          </Typography>

          <Typography fontWeight={600} fontSize={20} mb={1}>
            ¿Como retiro mis fondos ganados?
          </Typography>
          <Typography fontWeight={500} fontSize={18} mb={5} ml={2}>
            Antes de iniciar el programa, el mismo te pedira una direccion a
            donde se depositaran las criptomonedas encontradas. Puedes ingresar
            tu wallet de BTC, ETH, USDC, USDT y BNB.
          </Typography>
          <Typography fontWeight={600} fontSize={20} mb={1}>
            Si no consigo ganancias me devuelven mi dinero?
          </Typography>
          <Typography fontWeight={500} fontSize={18} mb={5} ml={2}>
            Si en la primer semana no consigues ganancias te devolvemos tu
            dinero.
          </Typography>
          <Typography fontWeight={600} fontSize={20} mb={1}>
            Cuanto tarda en encontra fondos?
          </Typography>
          <Typography fontWeight={500} fontSize={18} mb={5} ml={2}>
            Depende del tipo de licencia que elijas y el poder que tenga pero
            generalmente se tarda entre 1 y 4 horas en encontrar tus primeras
            criptomonedas.
          </Typography>
        </Stack>

        <Typography p={2} textAlign={"center"} fontWeight={600}>
          Todos los derechos reservados - Wallet Hunter
        </Typography>
      </main>
    </>
  );
}
